name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          uname -a
          sudo lspci
          sudo lscpu
          sudo ip a s
          sudo ss -lptn
          sudo netstat -lptn
          sudo free -m
